------------------------------------------------------------------------------
-- cordic_atan2.vhd
-- Pipelined vectoring-mode CORDIC: angle = atan2(y_in, x_in).
--
-- De Buda carrier loop phase detector. Operates on the mixed-down, low-passed
-- squared signal (the 2*fc tone). Output angle is the instantaneous phase of
-- that tone; the loop subtracts the NCO phase to form the carrier phase error.
--
-- Bit-exact to debuda_fixedpoint_model.py (same 16 stages, same ATAN_LUT, same
-- fold/unfold). Validated: 0.006 deg rms vs arctan2; 0% BER in the full chain.
--
-- Angle scale: full circle = 2^ANG_W, so the signed output spans
-- [-2^(ANG_W-1), 2^(ANG_W-1)) == [-pi, pi). This matches the 32-bit NCO phase
-- units, so the phase error feeds pi_controller with no rescaling.
--
-- Latency: STAGES+1 clocks (1 fold stage + STAGES iteration stages). valid_in
-- is pipelined to valid_out. Throughput: one result per clock.
--
-- Open Research Institute -- CERN-OHL-S-2.0
------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY cordic_atan2 IS
    GENERIC (
        XY_W   : NATURAL := 20;   -- input x/y width (signed)
        ANG_W  : NATURAL := 32;   -- output angle width; full circle = 2^ANG_W
        STAGES : NATURAL := 16    -- iterations (must match ATAN_LUT length)
    );
    PORT (
        clk       : IN  std_logic;
        valid_in  : IN  std_logic;
        x_in      : IN  signed(XY_W - 1 DOWNTO 0);
        y_in      : IN  signed(XY_W - 1 DOWNTO 0);
        valid_out : OUT std_logic;
        angle     : OUT signed(ANG_W - 1 DOWNTO 0)
    );
END ENTITY cordic_atan2;

ARCHITECTURE rtl OF cordic_atan2 IS

    -- internal datapath carries 2 guard bits for the fold negation and the
    -- CORDIC processing gain (~1.647, bounded).
    CONSTANT G : NATURAL := XY_W + 2;

    TYPE xy_arr_t  IS ARRAY (0 TO STAGES) OF signed(G - 1 DOWNTO 0);
    TYPE ang_arr_t IS ARRAY (0 TO STAGES) OF signed(ANG_W - 1 DOWNTO 0);

    SIGNAL xp   : xy_arr_t  := (OTHERS => (OTHERS => '0'));
    SIGNAL yp   : xy_arr_t  := (OTHERS => (OTHERS => '0'));
    SIGNAL ap   : ang_arr_t := (OTHERS => (OTHERS => '0'));
    SIGNAL negp : std_logic_vector(0 TO STAGES) := (OTHERS => '0');
    SIGNAL vp   : std_logic_vector(0 TO STAGES) := (OTHERS => '0');

    -- atan(2^-i) in angle units (full circle = 2^32). Generated by the model.
    TYPE lut_t IS ARRAY (0 TO 15) OF signed(31 DOWNTO 0);
    CONSTANT ATAN_LUT : lut_t := (
        x"20000000", x"12E4051E", x"09FB385B", x"051111D4",
        x"028B0D43", x"0145D7E1", x"00A2F61E", x"00517C55",
        x"0028BE53", x"00145F2F", x"000A2F98", x"000517CC",
        x"00028BE6", x"000145F3", x"0000A2FA", x"0000517D");

    -- MSB-only mask: +pi == flip MSB == add 2^(ANG_W-1) mod 2^ANG_W.
    -- Built by shift (not an aggregate) so the choice stays legal for a generic
    -- width, and to avoid the 2**(ANG_W-1) integer overflow at ANG_W=32.
    CONSTANT HALF_CIRCLE : std_logic_vector(ANG_W - 1 DOWNTO 0) :=
        std_logic_vector(shift_left(to_unsigned(1, ANG_W), ANG_W - 1));

BEGIN

    ASSERT STAGES = 16
        REPORT "cordic_atan2: ATAN_LUT has 16 entries; set STAGES=16 or extend the LUT."
        SEVERITY failure;

    pipe : PROCESS (clk)
    BEGIN
        IF rising_edge(clk) THEN

            -- stage 0: fold to x >= 0 (atan ratio preserved; +pi added on unfold)
            IF x_in(XY_W - 1) = '1' THEN          -- x < 0
                xp(0)   <= -resize(x_in, G);
                yp(0)   <= -resize(y_in, G);
                negp(0) <= '1';
            ELSE
                xp(0)   <= resize(x_in, G);
                yp(0)   <= resize(y_in, G);
                negp(0) <= '0';
            END IF;
            ap(0) <= (OTHERS => '0');
            vp(0) <= valid_in;

            -- iteration stages: drive y toward 0, accumulate the angle
            FOR i IN 0 TO STAGES - 1 LOOP
                IF yp(i)(G - 1) = '0' THEN        -- y >= 0: rotate by -atan(2^-i)
                    xp(i + 1) <= xp(i) + shift_right(yp(i), i);
                    yp(i + 1) <= yp(i) - shift_right(xp(i), i);
                    ap(i + 1) <= ap(i) + ATAN_LUT(i);
                ELSE                               -- y < 0: rotate by +atan(2^-i)
                    xp(i + 1) <= xp(i) - shift_right(yp(i), i);
                    yp(i + 1) <= yp(i) + shift_right(xp(i), i);
                    ap(i + 1) <= ap(i) - ATAN_LUT(i);
                END IF;
                negp(i + 1) <= negp(i);
                vp(i + 1)   <= vp(i);
            END LOOP;

        END IF;
    END PROCESS pipe;

    -- unfold: add pi (mod 2pi) when the input was folded. +2^(ANG_W-1) mod
    -- 2^ANG_W is exactly an MSB flip, so this never overflows.
    angle <= signed(std_logic_vector(ap(STAGES)) XOR HALF_CIRCLE)
                 WHEN negp(STAGES) = '1'
                 ELSE ap(STAGES);
    valid_out <= vp(STAGES);

END ARCHITECTURE rtl;
------------------------------------------------------------------------------
-- fir_lowpass_complex.vhd
-- Self-contained 25-tap symmetric (linear-phase) complex low-pass FIR for the
-- De Buda carrier front end. Contained here on purpose: no dependency on the
-- channelizer, so the demod ports to channelizer-free designs.
--
-- Isolates the 2*fc carrier tone (near DC) from the -54200 Hz squared image and
-- noise, on the mixed-down squared signal. Same real coefficients applied to I
-- and Q. Runs once per valid sample (rx_svalid), direct form.
--
-- Cutoff R/4 = 13550 Hz @ fs = 625 ksps. Passband -1.4 dB at +13550, image
-- -37.5 dB at -54200 (solid margin; the PI loop filter cleans the residual).
-- 25 taps matches the channel filter precedent. Coefficients and response
-- validated in debuda_fixedpoint_model.py at 0% BER (clean, +noise, +offset).
--
-- The CORDIC reads only the ANGLE of this output, so the FIR's absolute gain is
-- irrelevant -- only its frequency response matters. Output is kept full-width;
-- truncate downstream as convenient before cordic_atan2.
--
-- Open Research Institute -- CERN-OHL-S-2.0
------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY fir_lowpass_complex IS
    GENERIC (
        IN_W   : NATURAL := 20;   -- input I/Q width (mixed-down squared signal)
        COEF_W : NATURAL := 12    -- coefficient width (signed)
    );
    PORT (
        clk      : IN  std_logic;
        rst      : IN  std_logic;        -- synchronous, active high (rx_init)
        valid_in : IN  std_logic;        -- one pulse per channel sample (rx_svalid)
        i_in     : IN  signed(IN_W - 1 DOWNTO 0);
        q_in     : IN  signed(IN_W - 1 DOWNTO 0);
        valid_out: OUT std_logic;
        i_out    : OUT signed(IN_W + COEF_W + 4 DOWNTO 0);  -- full-width MAC result
        q_out    : OUT signed(IN_W + COEF_W + 4 DOWNTO 0)
    );
END ENTITY fir_lowpass_complex;

ARCHITECTURE rtl OF fir_lowpass_complex IS

    CONSTANT NTAPS : NATURAL := 25;

    -- symmetric windowed-sinc, cutoff R/4, 12-bit. Validated taps.
    TYPE coef_arr_t IS ARRAY (0 TO NTAPS - 1) OF signed(COEF_W - 1 DOWNTO 0);
    CONSTANT COEFS : coef_arr_t := (
        to_signed(    0, COEF_W), to_signed(   23, COEF_W), to_signed(   98, COEF_W),
        to_signed(  230, COEF_W), to_signed(  416, COEF_W), to_signed(  649, COEF_W),
        to_signed(  913, COEF_W), to_signed( 1191, COEF_W), to_signed( 1460, COEF_W),
        to_signed( 1699, COEF_W), to_signed( 1886, COEF_W), to_signed( 2006, COEF_W),
        to_signed( 2047, COEF_W), to_signed( 2006, COEF_W), to_signed( 1886, COEF_W),
        to_signed( 1699, COEF_W), to_signed( 1460, COEF_W), to_signed( 1191, COEF_W),
        to_signed(  913, COEF_W), to_signed(  649, COEF_W), to_signed(  416, COEF_W),
        to_signed(  230, COEF_W), to_signed(   98, COEF_W), to_signed(   23, COEF_W),
        to_signed(    0, COEF_W));

    CONSTANT ACC_W : NATURAL := IN_W + COEF_W + 5;   -- headroom for 25-tap sum (2^5 >= 25)

    TYPE dl_t IS ARRAY (0 TO NTAPS - 1) OF signed(IN_W - 1 DOWNTO 0);
    SIGNAL dl_i, dl_q : dl_t := (OTHERS => (OTHERS => '0'));
    SIGNAL v_d : std_logic := '0';

BEGIN

    PROCESS (clk)
        VARIABLE acc_i, acc_q : signed(ACC_W - 1 DOWNTO 0);
    BEGIN
        IF rising_edge(clk) THEN
            IF rst = '1' THEN
                dl_i <= (OTHERS => (OTHERS => '0'));
                dl_q <= (OTHERS => (OTHERS => '0'));
                v_d  <= '0';
            ELSIF valid_in = '1' THEN
                -- shift the delay lines by one sample
                dl_i <= signed(i_in) & dl_i(0 TO NTAPS - 2);
                dl_q <= signed(q_in) & dl_q(0 TO NTAPS - 2);
                -- multiply-accumulate (direct form; fold for DSP savings if needed)
                acc_i := (OTHERS => '0');
                acc_q := (OTHERS => '0');
                acc_i := resize(signed(i_in) * COEFS(0), ACC_W);
                acc_q := resize(signed(q_in) * COEFS(0), ACC_W);
                FOR t IN 1 TO NTAPS - 1 LOOP
                    acc_i := acc_i + resize(dl_i(t - 1) * COEFS(t), ACC_W);
                    acc_q := acc_q + resize(dl_q(t - 1) * COEFS(t), ACC_W);
                END LOOP;
                i_out <= resize(acc_i, i_out'length);
                q_out <= resize(acc_q, q_out'length);
                v_d   <= '1';
            ELSE
                v_d <= '0';
            END IF;
        END IF;
    END PROCESS;

    valid_out <= v_d;

END ARCHITECTURE rtl;
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
--  _______                             ________                                            ______
--  __  __ \________ _____ _______      ___  __ \_____ _____________ ______ ___________________  /_
--  _  / / /___  __ \_  _ \__  __ \     __  /_/ /_  _ \__  ___/_  _ \_  __ `/__  ___/_  ___/__  __ \
--  / /_/ / __  /_/ //  __/_  / / /     _  _, _/ /  __/_(__  ) /  __// /_/ / _  /    / /__  _  / / /
--  \____/  _  .___/ \___/ /_/ /_/      /_/ |_|  \___/ /____/  \___/ \__,_/  /_/     \___/  /_/ /_/
--          /_/
--                   ________                _____ _____ _____         _____
--                   ____  _/_______ __________  /____(_)__  /_____  ____  /______
--                    __  /  __  __ \__  ___/_  __/__  / _  __/_  / / /_  __/_  _ \
--                   __/ /   _  / / /_(__  ) / /_  _  /  / /_  / /_/ / / /_  /  __/
--                   /___/   /_/ /_/ /____/  \__/  /_/   \__/  \__,_/  \__/  \___/
--
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
-- Copyright
------------------------------------------------------------------------------------------------------
--
-- Copyright 2024 by M. Wishek <matthew@wishek.com>
--
------------------------------------------------------------------------------------------------------
-- License
------------------------------------------------------------------------------------------------------
--
-- This source describes Open Hardware and is licensed under the CERN-OHL-W v2.
--
-- You may redistribute and modify this source and make products using it under
-- the terms of the CERN-OHL-W v2 (https://ohwr.org/cern_ohl_w_v2.txt).
--
-- This source is distributed WITHOUT ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING
-- OF MERCHANTABILITY, SATISFACTORY QUALITY AND FITNESS FOR A PARTICULAR PURPOSE.
-- Please see the CERN-OHL-W v2 for applicable conditions.
--
-- Source location: TBD
--
-- As per CERN-OHL-W v2 section 4.1, should You produce hardware based on this
-- source, You must maintain the Source Location visible on the external case of
-- the products you make using this source.
--
------------------------------------------------------------------------------------------------------
-- Block name and description
------------------------------------------------------------------------------------------------------
--
-- This block implements and MSK Demodulator.
--
-- Documentation location: TBD
--
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------


------------------------------------------------------------------------------------------------------
-- ?  ??? ????????????????
-- ?  ???????????????? ???
-- ??????????? ???????????
------------------------------------------------------------------------------------------------------
-- Libraries

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
use std.textio.all;

------------------------------------------------------------------------------------------------------
-- ?????????????? ?
-- ?? ??? ? ? ? ???
-- ?????? ? ? ?  ? 
------------------------------------------------------------------------------------------------------
-- Entity

ENTITY msk_demodulator IS 
	GENERIC (
		NCO_W 			: NATURAL := 32;
		ACC_W 			: NATURAL := 32;
		PHASE_W 		: NATURAL := 10;
		SINUSOID_W 		: NATURAL := 12;
		SAMPLE_W 		: NATURAL := 12;
		DATA_W 			: NATURAL := 16;
		GAIN_W 			: NATURAL := 24;
		SHIFT_W 		: NATURAL := 8;
		SAMPLE_GATED_NCO	: BOOLEAN := False  -- FALSE = original; TRUE = sample-gate NCO (clk /= fs)
	);
	PORT (
		clk 				: IN  std_logic;
		init 				: IN  std_logic;

		rx_freq_word_f1 	: IN  std_logic_vector(NCO_W -1 DOWNTO 0);
		rx_freq_word_f2	 	: IN  std_logic_vector(NCO_W -1 DOWNTO 0);
		discard_rxnco 		: IN  std_logic_vector(7 DOWNTO 0);

		lpf_p_gain 			: IN  std_logic_vector(GAIN_W -1 DOWNTO 0);
		lpf_i_gain 			: IN  std_logic_vector(GAIN_W -1 DOWNTO 0);
		lpf_p_shift			: IN  std_logic_vector(SHIFT_W -1 DOWNTO 0);
		lpf_i_shift			: IN  std_logic_vector(SHIFT_W -1 DOWNTO 0);
		lpf_freeze 			: IN  std_logic;
		lpf_zero   			: IN  std_logic;
		lpf_alpha  			: IN  std_logic_vector(GAIN_W -1 DOWNTO 0);

		lpf_accum_f1		: OUT std_logic_vector(ACC_W -1 DOWNTO 0);
		lpf_accum_f2		: OUT std_logic_vector(ACC_W -1 DOWNTO 0);
		f1_nco_adjust		: OUT std_logic_vector(31 DOWNTO 0);
		f2_nco_adjust		: OUT std_logic_vector(31 DOWNTO 0);
		f1_error			: OUT std_logic_vector(31 DOWNTO 0);
		f2_error			: OUT std_logic_vector(31 DOWNTO 0);

		rx_dec_lbk_ena			: IN  std_logic;
		rx_dec_lbk_tclk			: IN  std_logic;
		rx_dec_lbk_f1			: IN  std_logic_vector(1 DOWNTO 0);
		rx_dec_lbk_f2			: IN  std_logic_vector(1 DOWNTO 0);

		rx_enable			: IN  std_logic;
		rx_svalid			: IN  std_logic;
		--rx_samples			: IN  std_logic_vector(SAMPLE_W -1 DOWNTO 0);
		rx_i_samples			: IN  std_logic_vector(SAMPLE_W -1 DOWNTO 0);
		rx_q_samples			: IN  std_logic_vector(SAMPLE_W -1 DOWNTO 0);

		rx_data				: OUT std_logic;           -- Keep for hard decision mode
		rx_data_soft			: OUT signed(15 DOWNTO 0); -- Full soft metric
		rx_dvalid			: OUT std_logic;

		symbol_lock_count		: IN  std_logic_vector(9 DOWNTO 0);
		symbol_lock_threshold	: IN  std_logic_vector(15 DOWNTO 0);

		cst_lock_f1 			: OUT std_logic;
		cst_lock_f2				: OUT std_logic;
		cst_lock_time_f1 		: OUT std_logic_vector(15 DOWNTO 0);
		cst_lock_time_f2 		: OUT std_logic_vector(15 DOWNTO 0);
		cst_unlock_f1 			: OUT std_logic;
		cst_unlock_f2 			: OUT std_logic;

		-- Ports added for ILA in order to calibrate symbol lock threshold
		-- I'm only putting in F1 because that should be sufficient
		dbg_acc_i_f1			: OUT std_logic_vector(ACC_W -1 DOWNTO 0);
		dbg_acc_q_f1			: OUT std_logic_vector(ACC_W -1 DOWNTO 0);
		dbg_acc_iq_delta_f1		: OUT std_logic_vector(ACC_W -1 DOWNTO 0)

	);
END ENTITY msk_demodulator;


------------------------------------------------------------------------------------------------------
-- ?????????? ??????????????? ???????
-- ???????  ???? ? ?? ?   ? ? ?????? 
-- ? ???????? ?? ? ?????? ? ?????????
------------------------------------------------------------------------------------------------------
-- Architecture

ARCHITECTURE rtl OF msk_demodulator IS 

	CONSTANT full_scale  	: unsigned(NCO_W -1 DOWNTO 0) := (OTHERS => '1');

	CONSTANT NCO_PId2 		: unsigned(NCO_W -1 DOWNTO 0) := full_scale/4;
	CONSTANT NCO_PI  		: unsigned(NCO_W -1 DOWNTO 0) := full_scale/2;
	CONSTANT NCO_3PId2		: unsigned(NCO_W -1 DOWNTO 0) := resize((full_scale*3)/2, NCO_W);
	CONSTANT NCO_2PI 		: unsigned(NCO_W -1 DOWNTO 0) := (OTHERS => '0');

	SIGNAL rx_init 			: std_logic;
	SIGNAL tclk 			: std_logic;
	SIGNAL data_f1  		: std_logic_vector(DATA_W -1 DOWNTO 0);
	SIGNAL data_f2  		: std_logic_vector(DATA_W -1 DOWNTO 0);
	SIGNAL data_f1_signed	: signed(DATA_W -1 DOWNTO 0);
	SIGNAL data_f2_signed	: signed(DATA_W -1 DOWNTO 0);
	SIGNAL data_f1_d 		: signed(DATA_W -1 DOWNTO 0);
	SIGNAL data_f2_d 		: signed(DATA_W -1 DOWNTO 0);
	SIGNAL data_f1_sum		: signed(DATA_W -1 DOWNTO 0);
	SIGNAL data_f2_sum		: signed(DATA_W -1 DOWNTO 0);
	SIGNAL data_f1_T		: signed(DATA_W -1 DOWNTO 0);
	SIGNAL data_f2_T		: signed(DATA_W -1 DOWNTO 0);
	SIGNAL data_sum 		: signed(DATA_W -1 DOWNTO 0);
	SIGNAL data_bit 		: std_logic;
	SIGNAL data_bit_enc 	: std_logic;
	SIGNAL data_bit_enc_t	: std_logic;
	SIGNAL data_bit_dec		: std_logic;
	SIGNAL data_dec 		: std_logic;
	SIGNAL tclk_dly 		: std_logic_vector(0 TO 3);
	SIGNAL rx_cos_f1 		: std_logic_vector(SINUSOID_W -1 DOWNTO 0);
	SIGNAL rx_cos_f2 		: std_logic_vector(SINUSOID_W -1 DOWNTO 0);
	SIGNAL rx_sin_f1 		: std_logic_vector(SINUSOID_W -1 DOWNTO 0);
	SIGNAL rx_sin_f2 		: std_logic_vector(SINUSOID_W -1 DOWNTO 0);
	SIGNAL rx_cos_f1_sin_f2 : signed(2*SINUSOID_W -1 DOWNTO 0);
	SIGNAL rx_cos_f2_sin_f1 : signed(2*SINUSOID_W -1 DOWNTO 0);
	SIGNAL rx_cos_f1_cos_f2 : signed(2*SINUSOID_W -1 DOWNTO 0);
	SIGNAL rx_sin_f1_sin_f2 : signed(2*SINUSOID_W -1 DOWNTO 0);
	SIGNAL dclk_slv			: signed(2*SINUSOID_W -1 DOWNTO 0);
	SIGNAL cclk_slv			: signed(2*SINUSOID_W -1 DOWNTO 0);
	SIGNAL dclk 			: std_logic;
	SIGNAL dclk_d 			: std_logic;
	SIGNAL cclk 			: std_logic;
	SIGNAL error_valid_f1 	: std_logic;
	SIGNAL error_valid_f2 	: std_logic;

	SIGNAL lbk_f1_T 		: signed(2 DOWNTO 0);
	SIGNAL lbk_f2_T 		: signed(2 DOWNTO 0);
	SIGNAL lbk_f1_sum		: signed(2 DOWNTO 0);
	SIGNAL lbk_f2_sum		: signed(2 DOWNTO 0);
	SIGNAL lbk_sum			: signed(2 DOWNTO 0);
	SIGNAL lbk_bit_enc_T 	: signed(1 DOWNTO 0);
	SIGNAL lbk_tclk 		: std_logic_vector(0 TO 3);
	SIGNAL lbk_bit_enc 		: signed(1 DOWNTO 0);
	SIGNAL lbk_bit_dec		: std_logic;
	SIGNAL lbk_f1_signed 	: signed(2 DOWNTO 0);
	SIGNAL lbk_f2_signed 	: signed(2 DOWNTO 0);

        SIGNAL f1_error_int, f2_error_int : std_logic_vector(31 DOWNTO 0);
        SIGNAL ev_f1_d, ev_f2_d  : std_logic;                          -- error_valid delayed 1 clk
        SIGNAL common_err        : std_logic_vector(31 DOWNTO 0);
        SIGNAL common_err_valid  : std_logic;
        SIGNAL common_adjust     : std_logic_vector(NCO_W -1 DOWNTO 0);
        SIGNAL common_adj_valid  : std_logic;
        CONSTANT GAIN_ZERO       : std_logic_vector(GAIN_W - 1 DOWNTO 0) := (OTHERS => '0');

        -- de Buda integration
        CONSTANT DBU_MIX_FREQ         : std_logic_vector(NCO_W-1 DOWNTO 0) := x"0B19A416";
                                             -- round(27100/625000 * 2^32), fixed mixer
        CONSTANT DBU_FIR_IN_W         : NATURAL := 18;  -- top bits of the 38b mixer bus
        CONSTANT DBU_XY_W             : NATURAL := 18;  -- top bits of the 35b FIR bus

        SIGNAL dbu_sq_re, dbu_sq_im   : signed(2*SAMPLE_W DOWNTO 0);                  -- 25b
        SIGNAL dbu_sq_valid           : std_logic;
        SIGNAL dbu_mix_phase          : std_logic_vector(NCO_W-1 DOWNTO 0);
        SIGNAL dbu_mix_cos, dbu_mix_sin : std_logic_vector(SINUSOID_W-1 DOWNTO 0);
        SIGNAL dbu_mix_re, dbu_mix_im : signed(2*SAMPLE_W + SINUSOID_W + 1 DOWNTO 0); -- 38b
        SIGNAL dbu_mix_valid          : std_logic;
        SIGNAL dbu_fir_i, dbu_fir_q   : signed(DBU_FIR_IN_W + 12 + 4 DOWNTO 0);       -- 35b
        SIGNAL dbu_fir_valid          : std_logic;
        SIGNAL dbu_angle              : signed(31 DOWNTO 0);
        SIGNAL dbu_angle_valid        : std_logic;
        SIGNAL dbu_phase              : signed(31 DOWNTO 0);   -- De Buda NCO phase (2fc)
        SIGNAL pi_out                 : std_logic_vector(NCO_W-1 DOWNTO 0);  -- shared PI output



BEGIN

	rx_init 		<= init OR NOT rx_enable;






  -- synthesis translate_off
  -- DEBUG ONLY: dump De Buda input (rx_i/rx_q) for oracle comparison.
  -- Captures 1024 samples then closes the file so the data is flushed
  -- even if the run is stopped early. Never synthesized.
  dbu_rx_dump_proc : process(clk)
      file     fdump  : text open write_mode is "debuda_rx_dump.txt";
      variable l      : line;
      variable n      : integer := 0;
      variable done   : boolean := false;
  begin
      if rising_edge(clk) then
          if rx_svalid = '1' and not done then
              write(l, to_integer(signed(rx_i_samples)));
              write(l, string'(","));
              write(l, to_integer(signed(rx_q_samples)));
              writeline(fdump, l);
              n := n + 1;
              if n >= 1024 then
                  file_close(fdump);
                  done := true;
              end if;
          end if;
      end if;
  end process;
  -- synthesis translate_on










------------------------------------------------------------------------------------------------------
--  __       ___         __   __  __  __   __   __ 
-- |  \  /\   |   /\    |  \ |_  /   /  \ |  \ |_  
-- |__/ /--\  |  /--\   |__/ |__ \__ \__/ |__/ |__ 
--                                                 
------------------------------------------------------------------------------------------------------
-- Data Decode

 	data_f1_signed 	<= signed(data_f1);
	data_f2_signed 	<= signed(NOT data_f2) + 1 WHEN cclk = '0' ELSE signed(data_f2);

	data_proc : PROCESS (clk)
	BEGIN
		IF clk'EVENT AND clk = '1' THEN

			tclk_dly 	 <= tclk  			& tclk_dly(0 TO 2);

			IF tclk = '1' THEN
	
				data_f1_T <= data_f1_signed;
				data_f2_T <= data_f2_signed;
	
			END IF;

			IF tclk_dly(0) = '1' THEN
		
				data_f1_sum <= signed(data_f1_signed) + data_f1_T;
				data_f2_sum <= signed(data_f2_signed) + data_f2_T;
		
			END IF;

			IF tclk_dly(0) = '1' THEN 
				data_bit_enc_t <= data_bit_enc;
			END IF;

			IF rx_init = '1' THEN
				data_f1_T 		<= (OTHERS => '0');
				data_f2_T 		<= (OTHERS => '0');
				data_f1_sum		<= (OTHERS => '0');
				data_f2_sum		<= (OTHERS => '0');
				data_bit_enc_t 	<= '0';
			END IF;

		END IF;
	END PROCESS data_proc;

	data_sum 	<= signed(data_f1_sum) - signed(data_f2_sum); -- 16 bit signed
	data_bit_enc 	<= data_sum(DATA_W -1);                       -- currently only using sign bit
	data_bit_dec	<= data_bit_enc WHEN data_bit_enc_t = '0' ELSE NOT data_bit_enc;


 	lbk_f1_signed 	<= resize(signed(    rx_dec_lbk_f1),     lbk_f1_signed'LENGTH);
	lbk_f2_signed 	<= resize(signed(NOT rx_dec_lbk_f2) + 1, lbk_f2_signed'LENGTH) WHEN cclk = '0' ELSE 
	 				   resize(signed(    rx_dec_lbk_f2),     lbk_f2_signed'LENGTH);

	loopback_data_proc : PROCESS (clk)
	BEGIN
		IF clk'EVENT AND clk = '1' THEN

			IF rx_dec_lbk_ena = '1' THEN

				lbk_tclk	<= rx_dec_lbk_tclk	& lbk_tclk(0 TO 2);

				IF rx_dec_lbk_tclk = '1' THEN
	
					lbk_f1_T <= signed(lbk_f1_signed);
					lbk_f2_T <= signed(lbk_f2_signed);
			
					lbk_f1_sum <= signed(lbk_f1_signed) + lbk_f1_T;
					lbk_f2_sum <= signed(lbk_f2_signed) + lbk_f2_T;
				
					lbk_bit_enc_T <= lbk_bit_enc;

				END IF;

			END IF;

			IF rx_init = '1' THEN
				lbk_f1_T 		<= (OTHERS => '0');
				lbk_f2_T 		<= (OTHERS => '0');
				lbk_f1_sum		<= (OTHERS => '0');
				lbk_f2_sum		<= (OTHERS => '0');
				lbk_bit_enc_T 	<= (OTHERS => '0');
			END IF;

		END IF;
	END PROCESS loopback_data_proc;

	lbk_sum 		<= signed(lbk_f1_sum) - signed(lbk_f2_sum);
	lbk_bit_enc 	<= "01" WHEN lbk_sum(2) = '0' ELSE "11";
	lbk_bit_dec		<= lbk_bit_enc(1) XOR lbk_bit_enc_T(1);

	rx_data 		<= data_bit_dec WHEN rx_dec_lbk_ena = '0' ELSE lbk_bit_dec;
	-- Soft value must also be differentially decoded to match hard decision!
	-- When data_bit_enc_t = '1' (previous bit was negative), flip the soft sign
	rx_data_soft		<= data_sum WHEN data_bit_enc_t = '0' ELSE -data_sum;

	rx_dvalid 		<= tclk_dly(1)  WHEN rx_dec_lbk_ena = '0' ELSE lbk_tclk(1);

	error_valid_f1 	<= tclk_dly(1) AND NOT(data_bit_dec) WHEN rx_dec_lbk_ena = '0' ELSE
					   lbk_tclk(1) AND NOT(lbk_bit_dec);
	error_valid_f2 	<= tclk_dly(1) AND data_bit_dec      WHEN rx_dec_lbk_ena = '0' ELSE
					   lbk_tclk(1) AND lbk_bit_dec;


------------------------------------------------------------------------------------------------------
--  __           __   __         __      __   __        __   __  __  __        __  __      
-- (_  \_/ |\/| |__) /  \ |     /   |   /  \ /   |_/   |__) |_  /   /  \ \  / |_  |__) \_/ 
-- __)  |  |  | |__) \__/ |__   \__ |__ \__/ \__ | \   | \  |__ \__ \__/  \/  |__ | \   |  
--                                                                                         
------------------------------------------------------------------------------------------------------
-- Symbol Clock Recovery

	tclk <= dclk XOR dclk_d WHEN rx_dec_lbk_ena = '0' ELSE rx_dec_lbk_tclk;

	clock_rec_process : PROCESS (clk)
	BEGIN
		IF clk'EVENT AND clk = '1' THEN

			rx_cos_f1_sin_f2 <= signed(rx_cos_f1) * signed(rx_sin_f2);
			rx_cos_f2_sin_f1 <= signed(rx_cos_f2) * signed(rx_sin_f1);
			rx_cos_f1_cos_f2 <= signed(rx_cos_f1) * signed(rx_cos_f2);
			rx_sin_f1_sin_f2 <= signed(rx_sin_f2) * signed(rx_sin_f1);

			dclk_slv <= rx_cos_f1_sin_f2 - rx_cos_f2_sin_f1;
			cclk_slv <= rx_cos_f1_cos_f2 + rx_sin_f1_sin_f2;

			dclk <= NOT dclk_slv(2*SINUSOID_W -1);
			cclk <= NOT cclk_slv(2*SINUSOID_W -1);

			dclk_d <= dclk;

			IF init = '1' THEN

				rx_cos_f1_sin_f2 	<= (OTHERS => '0');
				rx_cos_f2_sin_f1 	<= (OTHERS => '0');
				rx_cos_f1_cos_f2 	<= (OTHERS => '0');
				rx_sin_f1_sin_f2 	<= (OTHERS => '0');
				dclk_slv			<= (OTHERS => '0');
				cclk_slv			<= (OTHERS => '0');
				dclk				<= '0';
				cclk				<= '0';
				dclk_d				<= '0';

			END IF;
		END IF;
	END PROCESS clock_rec_process;

err_align : PROCESS (clk)
    BEGIN
        IF rising_edge(clk) THEN
            ev_f1_d <= error_valid_f1;
            ev_f2_d <= error_valid_f2;
            IF rx_init = '1' THEN
                ev_f1_d <= '0';
                ev_f2_d <= '0';
            END IF;
        END IF;
    END PROCESS;

    -- whichever loop produced a valid error this symbol drives the shared loop
    f1_error   <= f1_error_int;  -- left in for debug
    f2_error   <= f2_error_int;  -- left in for debug
    --common_err <= f1_error_int WHEN ev_f1_d = '1' ELSE f2_error_int;  -- now driven by dbu_loop_proc above
    --common_err_valid <= ev_f1_d OR ev_f2_d;                           -- now driven by dbu_loop_proc above






  -- ---- squarer:  z^2 = (i^2 - q^2) + j*(2*i*q)  (the modulation stripper) ----
  dbu_square_proc : PROCESS (clk)
  BEGIN
      IF rising_edge(clk) THEN
          IF rx_init = '1' THEN
              dbu_sq_valid <= '0';
          ELSIF rx_svalid = '1' THEN
              dbu_sq_re <= resize(signed(rx_i_samples)*signed(rx_i_samples), dbu_sq_re'length)
                         - resize(signed(rx_q_samples)*signed(rx_q_samples), dbu_sq_re'length);
              dbu_sq_im <= resize(shift_left(signed(rx_i_samples)*signed(rx_q_samples), 1),
                                  dbu_sq_im'length);
              dbu_sq_valid <= '1';
          ELSE
              dbu_sq_valid <= '0';
          END IF;
      END IF;
  END PROCESS;

  -- ---- fixed mixer NCO @ R/2 (reuse the design's nco + sin_cos_lut) ----
  U_dbu_mix_nco : ENTITY work.nco(rtl)
      GENERIC MAP ( NCO_W => NCO_W, PHASE_INIT => (OTHERS => '0') )
      PORT MAP (
          clk => clk, init => rx_init,
          enable          => rx_svalid,          -- advance once per channel sample
          discard_nco     => (OTHERS => '0'),
          freq_word       => DBU_MIX_FREQ,
          freq_adj_zero   => '1',                -- fixed frequency: no loop adjust
          freq_adj_valid  => '0',
          freq_adjust     => (OTHERS => '0'),
          phase           => dbu_mix_phase,
          rollover_pi2 => OPEN, rollover_pi => OPEN, rollover_3pi2 => OPEN,
          rollover_2pi => OPEN, tclk_even => OPEN, tclk_odd => OPEN );

  U_dbu_mix_lut : ENTITY work.sin_cos_lut(lut_based)
      GENERIC MAP ( PHASE_W => PHASE_W, PHASES => 2**PHASE_W, SINUSOID_W => SINUSOID_W )
      PORT MAP (
          clk => clk, init => rx_init,
          phase   => dbu_mix_phase(NCO_W-1 DOWNTO NCO_W - PHASE_W),
          sin_out => dbu_mix_sin,
          cos_out => dbu_mix_cos );

  -- ---- complex down-mix: (sq)*(cos - j sin) ----
  dbu_mix_proc : PROCESS (clk)
  BEGIN
      IF rising_edge(clk) THEN
          IF rx_init = '1' THEN
              dbu_mix_valid <= '0';
          ELSIF dbu_sq_valid = '1' THEN
              dbu_mix_re <= resize(dbu_sq_re * signed(dbu_mix_cos), dbu_mix_re'length)
                          + resize(dbu_sq_im * signed(dbu_mix_sin), dbu_mix_re'length);
              dbu_mix_im <= resize(dbu_sq_im * signed(dbu_mix_cos), dbu_mix_im'length)
                          - resize(dbu_sq_re * signed(dbu_mix_sin), dbu_mix_im'length);
              dbu_mix_valid <= '1';
          ELSE
              dbu_mix_valid <= '0';
          END IF;
      END IF;
  END PROCESS;

  -- ---- contained low-pass FIR (top 18 bits of the 38b mixer bus) ----
  U_dbu_fir : ENTITY work.fir_lowpass_complex(rtl)
      GENERIC MAP ( IN_W => DBU_FIR_IN_W, COEF_W => 12 )
      PORT MAP (
          clk => clk, rst => rx_init, valid_in => dbu_mix_valid,
          i_in  => dbu_mix_re(dbu_mix_re'high DOWNTO dbu_mix_re'high - DBU_FIR_IN_W + 1),
          q_in  => dbu_mix_im(dbu_mix_im'high DOWNTO dbu_mix_im'high - DBU_FIR_IN_W + 1),
          valid_out => dbu_fir_valid, i_out => dbu_fir_i, q_out => dbu_fir_q );

  -- ---- CORDIC phase detector (top 18 bits of the 35b FIR bus) ----
  U_dbu_cordic : ENTITY work.cordic_atan2(rtl)
      GENERIC MAP ( XY_W => DBU_XY_W, ANG_W => 32, STAGES => 16 )
      PORT MAP (
          clk => clk, valid_in => dbu_fir_valid,
          x_in => dbu_fir_i(dbu_fir_i'high DOWNTO dbu_fir_i'high - DBU_XY_W + 1),
          y_in => dbu_fir_q(dbu_fir_q'high DOWNTO dbu_fir_q'high - DBU_XY_W + 1),
          valid_out => dbu_angle_valid, angle => dbu_angle );

  -- ---- De Buda NCO (2fc) + phase error.  32b signed subtract wraps == wrap32 ----
  dbu_loop_proc : PROCESS (clk)
  BEGIN
      IF rising_edge(clk) THEN
          IF rx_init = '1' THEN
              dbu_phase        <= (OTHERS => '0');
              common_err_valid <= '0';
          ELSE
              -- form the carrier phase error this sample
              IF dbu_angle_valid = '1' THEN
                  common_err       <= std_logic_vector(dbu_angle - dbu_phase);
                  common_err_valid <= '1';
              ELSE
                  common_err_valid <= '0';
              END IF;
              -- advance the 2fc NCO by the full PI output once it is valid
              IF common_adj_valid = '1' THEN
                  dbu_phase <= dbu_phase + signed(pi_out);
              END IF;
          END IF;
      END IF;
  END PROCESS;


















u_carrier_filter : ENTITY work.pi_controller(rtl)
    GENERIC MAP (
        NCO_W      => NCO_W,
        ERR_W      => 32,     -- warning hardcode alert!
        GAIN_W     => GAIN_W,
        ASSERT_ENA => False
    )
    PORT MAP (
        clk            => clk,
        init           => rx_init,
        enable         => rx_enable,
        lpf_p_gain     => lpf_p_gain,
        lpf_i_gain     => lpf_i_gain,
        lpf_i_shift    => lpf_i_shift,
        lpf_p_shift    => lpf_p_shift,
        lpf_freeze     => lpf_freeze,
        lpf_zero       => lpf_zero,
        lpf_err_valid  => common_err_valid,
        lpf_err        => common_err,
        lpf_adj_valid  => common_adj_valid,
        --lpf_adjust     => common_adjust,
        lpf_adjust     => pi_out, -- take the FULL PI output into pi_out instead of straight to common_adjust
        lpf_accum      => OPEN          -- (optionally route to a debug port)
        --lpf_p_gain     => GAIN_ZERO      -- coupled: common loop is integral-only (shared carrier frequency)
    );


    common_adjust <= std_logic_vector(shift_right(signed(pi_out), 1)); -- added as a concurrant assignment


------------------------------------------------------------------------------------------------------
--  __  __   __ ___       __        __   __   __     __     
-- /   /  \ (_   |   /\  (_    |   /  \ /  \ |__)   |_   /| 
-- \__ \__/ __)  |  /--\ __)   |__ \__/ \__/ |      |     | 
--                                                          
------------------------------------------------------------------------------------------------------
-- Costas Loop F1

	U_f1 : ENTITY work.costas_loop(rtl)
		GENERIC MAP (
			NCO_W 			=> NCO_W,
			ACC_W 		 	=> ACC_W,
			PHASE_W 		=> PHASE_W,
			SINUSOID_W 		=> SINUSOID_W,
			SAMPLE_W 		=> SAMPLE_W,
			DATA_W 			=> DATA_W,
			PHASE_INIT 		=> NCO_2PI,
                        EXTERNAL_NCO_ADJUST     => True,
			SAMPLE_GATED_NCO	=> SAMPLE_GATED_NCO
		)
		PORT MAP (
			clk 			=> clk,
			init 			=> rx_init,

			enable 			=> rx_enable,

			tclk 			=> tclk,

			lpf_p_gain 		=> lpf_p_gain,
			lpf_i_gain 		=> lpf_i_gain,
			lpf_i_shift		=> lpf_i_shift,
			lpf_p_shift		=> lpf_p_shift,
			lpf_freeze 	 	=> lpf_freeze,
			lpf_zero 		=> lpf_zero,
			lpf_alpha 		=> lpf_alpha,

			lpf_accum 		=> lpf_accum_f1,
			nco_adjust 		=> f1_nco_adjust,
                        loop_error		=> f1_error_int,

			discard_rxnco 	=> discard_rxnco,
			freq_word 		=> rx_freq_word_f1,
			cos_samples 	=> rx_cos_f1,
			sin_samples 	=> rx_sin_f1,

			error_valid		=> error_valid_f1,

			rx_svalid 		=> rx_svalid,
			--rx_samples 		=> rx_samples,
			rx_i_samples    => rx_i_samples,
			rx_q_samples    => rx_q_samples,

			data_out 		=> data_f1,

			symbol_lock_count		=> symbol_lock_count,
			symbol_lock_threshold	=> symbol_lock_threshold,

			cst_lock				=> cst_lock_f1,
			cst_lock_time 			=> cst_lock_time_f1,
			cst_unlock 				=> cst_unlock_f1,

                        ext_adjust       => common_adjust,
                        ext_adjust_valid => common_adj_valid,

			-- Port mapping added for ILA in order to calibrate symbol lock threshold
			dbg_acc_i => dbg_acc_i_f1,
			dbg_acc_q => dbg_acc_q_f1,
			dbg_acc_iq_delta => dbg_acc_iq_delta_f1

		);


------------------------------------------------------------------------------------------------------
--  __  __   __ ___       __        __   __   __     __  __  
-- /   /  \ (_   |   /\  (_    |   /  \ /  \ |__)   |_    _) 
-- \__ \__/ __)  |  /--\ __)   |__ \__/ \__/ |      |    /__ 
--                                                           
------------------------------------------------------------------------------------------------------
-- Costas Loop F2
                                                                              
	U_f2 : ENTITY work.costas_loop(rtl)
		GENERIC MAP (
			NCO_W 			=> NCO_W,
			ACC_W 		 	=> ACC_W,
			PHASE_W 		=> PHASE_W,
			SINUSOID_W 		=> SINUSOID_W,
			SAMPLE_W 		=> SAMPLE_W,
			DATA_W 			=> DATA_W,
			PHASE_INIT 		=> NCO_2PI,
                        EXTERNAL_NCO_ADJUST     => True,
			SAMPLE_GATED_NCO	=> SAMPLE_GATED_NCO
		)
		PORT MAP (
			clk 			=> clk,
			init 			=> rx_init,

			enable 			=> rx_enable,

			tclk 			=> tclk,

			lpf_p_gain 		=> lpf_p_gain,
			lpf_i_gain 		=> lpf_i_gain,
			lpf_i_shift		=> lpf_i_shift,
			lpf_p_shift		=> lpf_p_shift,
			lpf_freeze 	 	=> lpf_freeze,
			lpf_zero 		=> lpf_zero,
			lpf_alpha 		=> lpf_alpha,

			lpf_accum 		=> lpf_accum_f2,
			nco_adjust 		=> f2_nco_adjust,
                        loop_error		=> f2_error_int,

			discard_rxnco 	=> discard_rxnco,
			freq_word 		=> rx_freq_word_f2,
			cos_samples 	=> rx_cos_f2,
			sin_samples 	=> rx_sin_f2,

			error_valid 	=> error_valid_f2,

			rx_svalid 		=> rx_svalid,
			--rx_samples 		=> rx_samples,
			rx_i_samples    => rx_i_samples,
			rx_q_samples    => rx_q_samples,

			data_out 		=> data_f2,

			symbol_lock_count		=> symbol_lock_count,
			symbol_lock_threshold	=> symbol_lock_threshold,

			cst_lock				=> cst_lock_f2,
			cst_lock_time 			=> cst_lock_time_f2,
			cst_unlock 				=> cst_unlock_f2,

                        ext_adjust       => common_adjust,
                        ext_adjust_valid => common_adj_valid,

			-- Port mapping added for ILA in order to calibrate symbol lock threshold
			-- connect to open because we are planning on using F1 only for threshold calibration
			dbg_acc_i => open,
			dbg_acc_q => open,
			dbg_acc_iq_delta => open

		);

END ARCHITECTURE rtl;
