------------------------------------------------------------------------------------------------------
-- cordic_atan2 (bundled) + msk_demodulator in ONE file -- drop-in, no separate cordic needed.
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------
-- cordic_atan2.vhd
-- Pipelined vectoring-mode CORDIC: angle = atan2(y_in, x_in).
--
-- De Buda carrier loop phase detector. Operates on the mixed-down, low-passed
-- squared signal (the 2*fc tone). Output angle is the instantaneous phase of
-- that tone; the loop subtracts the NCO phase to form the carrier phase error.
--
-- Bit-exact to debuda_fixedpoint_model.py (same 16 stages, same ATAN_LUT, same
-- fold/unfold). Validated: 0.006 deg rms vs arctan2; 0% BER in the full chain.
--
-- Angle scale: full circle = 2^ANG_W, so the signed output spans
-- [-2^(ANG_W-1), 2^(ANG_W-1)) == [-pi, pi). This matches the 32-bit NCO phase
-- units, so the phase error feeds pi_controller with no rescaling.
--
-- Latency: STAGES+1 clocks (1 fold stage + STAGES iteration stages). valid_in
-- is pipelined to valid_out. Throughput: one result per clock.
--
-- Open Research Institute -- CERN-OHL-S-2.0
------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY cordic_atan2 IS
    GENERIC (
        XY_W   : NATURAL := 20;   -- input x/y width (signed)
        ANG_W  : NATURAL := 32;   -- output angle width; full circle = 2^ANG_W
        STAGES : NATURAL := 16    -- iterations (must match ATAN_LUT length)
    );
    PORT (
        clk       : IN  std_logic;
        valid_in  : IN  std_logic;
        x_in      : IN  signed(XY_W - 1 DOWNTO 0);
        y_in      : IN  signed(XY_W - 1 DOWNTO 0);
        valid_out : OUT std_logic;
        angle     : OUT signed(ANG_W - 1 DOWNTO 0)
    );
END ENTITY cordic_atan2;

ARCHITECTURE rtl OF cordic_atan2 IS

    -- internal datapath carries 2 guard bits for the fold negation and the
    -- CORDIC processing gain (~1.647, bounded).
    CONSTANT G : NATURAL := XY_W + 2;

    TYPE xy_arr_t  IS ARRAY (0 TO STAGES) OF signed(G - 1 DOWNTO 0);
    TYPE ang_arr_t IS ARRAY (0 TO STAGES) OF signed(ANG_W - 1 DOWNTO 0);

    SIGNAL xp   : xy_arr_t  := (OTHERS => (OTHERS => '0'));
    SIGNAL yp   : xy_arr_t  := (OTHERS => (OTHERS => '0'));
    SIGNAL ap   : ang_arr_t := (OTHERS => (OTHERS => '0'));
    SIGNAL negp : std_logic_vector(0 TO STAGES) := (OTHERS => '0');
    SIGNAL vp   : std_logic_vector(0 TO STAGES) := (OTHERS => '0');

    -- atan(2^-i) in angle units (full circle = 2^32). Generated by the model.
    TYPE lut_t IS ARRAY (0 TO 15) OF signed(31 DOWNTO 0);
    CONSTANT ATAN_LUT : lut_t := (
        x"20000000", x"12E4051E", x"09FB385B", x"051111D4",
        x"028B0D43", x"0145D7E1", x"00A2F61E", x"00517C55",
        x"0028BE53", x"00145F2F", x"000A2F98", x"000517CC",
        x"00028BE6", x"000145F3", x"0000A2FA", x"0000517D");

    -- MSB-only mask: +pi == flip MSB == add 2^(ANG_W-1) mod 2^ANG_W.
    -- Built by shift (not an aggregate) so the choice stays legal for a generic
    -- width, and to avoid the 2**(ANG_W-1) integer overflow at ANG_W=32.
    CONSTANT HALF_CIRCLE : std_logic_vector(ANG_W - 1 DOWNTO 0) :=
        std_logic_vector(shift_left(to_unsigned(1, ANG_W), ANG_W - 1));

BEGIN

    ASSERT STAGES = 16
        REPORT "cordic_atan2: ATAN_LUT has 16 entries; set STAGES=16 or extend the LUT."
        SEVERITY failure;

    pipe : PROCESS (clk)
    BEGIN
        IF rising_edge(clk) THEN

            -- stage 0: fold to x >= 0 (atan ratio preserved; +pi added on unfold)
            IF x_in(XY_W - 1) = '1' THEN          -- x < 0
                xp(0)   <= -resize(x_in, G);
                yp(0)   <= -resize(y_in, G);
                negp(0) <= '1';
            ELSE
                xp(0)   <= resize(x_in, G);
                yp(0)   <= resize(y_in, G);
                negp(0) <= '0';
            END IF;
            ap(0) <= (OTHERS => '0');
            vp(0) <= valid_in;

            -- iteration stages: drive y toward 0, accumulate the angle
            FOR i IN 0 TO STAGES - 1 LOOP
                IF yp(i)(G - 1) = '0' THEN        -- y >= 0: rotate by -atan(2^-i)
                    xp(i + 1) <= xp(i) + shift_right(yp(i), i);
                    yp(i + 1) <= yp(i) - shift_right(xp(i), i);
                    ap(i + 1) <= ap(i) + ATAN_LUT(i);
                ELSE                               -- y < 0: rotate by +atan(2^-i)
                    xp(i + 1) <= xp(i) - shift_right(yp(i), i);
                    yp(i + 1) <= yp(i) + shift_right(xp(i), i);
                    ap(i + 1) <= ap(i) - ATAN_LUT(i);
                END IF;
                negp(i + 1) <= negp(i);
                vp(i + 1)   <= vp(i);
            END LOOP;

        END IF;
    END PROCESS pipe;

    -- unfold: add pi (mod 2pi) when the input was folded. +2^(ANG_W-1) mod
    -- 2^ANG_W is exactly an MSB flip, so this never overflows.
    angle <= signed(std_logic_vector(ap(STAGES)) XOR HALF_CIRCLE)
                 WHEN negp(STAGES) = '1'
                 ELSE ap(STAGES);
    valid_out <= vp(STAGES);

END ARCHITECTURE rtl;


------------------------------------------------------------------------------------------------------
-- msk_demodulator.vhd : COHERENT MSK demodulator, FULLY SYNTHESIZABLE (drop-in, same entity).
-- Coherent common-carrier detection, data-phase subtraction, coherent decision, real cordic_atan2
-- (async), sin/cos ROM (elaboration-built), direct decode. Startup phase search is a MULTI-CYCLE
-- FSM (one buffer-sample per clock) -- no unrolled combinational block. No runtime real math.
-- rx_freq_word_f1/f2 carry R/4 = (f1-f2)/2 and carrier offset = (f1+f2)/2.
------------------------------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
USE ieee.math_real.ALL;   -- ONLY for the elaboration-time ROM constant

ENTITY msk_demodulator IS 
	GENERIC (
		NCO_W 			: NATURAL := 32;
		ACC_W 			: NATURAL := 32;
		PHASE_W 		: NATURAL := 10;
		SINUSOID_W 		: NATURAL := 12;
		SAMPLE_W 		: NATURAL := 12;
		DATA_W 			: NATURAL := 16;
		GAIN_W 			: NATURAL := 24;
		SHIFT_W 		: NATURAL := 8;
		SAMPLE_GATED_NCO	: BOOLEAN := False  -- FALSE = original; TRUE = sample-gate NCO (clk /= fs)
	);
	PORT (
		clk 				: IN  std_logic;
		init 				: IN  std_logic;

		rx_freq_word_f1 	: IN  std_logic_vector(NCO_W -1 DOWNTO 0);
		rx_freq_word_f2	 	: IN  std_logic_vector(NCO_W -1 DOWNTO 0);
		discard_rxnco 		: IN  std_logic_vector(7 DOWNTO 0);

		lpf_p_gain 			: IN  std_logic_vector(GAIN_W -1 DOWNTO 0);
		lpf_i_gain 			: IN  std_logic_vector(GAIN_W -1 DOWNTO 0);
		lpf_p_shift			: IN  std_logic_vector(SHIFT_W -1 DOWNTO 0);
		lpf_i_shift			: IN  std_logic_vector(SHIFT_W -1 DOWNTO 0);
		lpf_freeze 			: IN  std_logic;
		lpf_zero   			: IN  std_logic;
		lpf_alpha  			: IN  std_logic_vector(GAIN_W -1 DOWNTO 0);

		lpf_accum_f1		: OUT std_logic_vector(ACC_W -1 DOWNTO 0);
		lpf_accum_f2		: OUT std_logic_vector(ACC_W -1 DOWNTO 0);
		f1_nco_adjust		: OUT std_logic_vector(31 DOWNTO 0);
		f2_nco_adjust		: OUT std_logic_vector(31 DOWNTO 0);
		f1_error			: OUT std_logic_vector(31 DOWNTO 0);
		f2_error			: OUT std_logic_vector(31 DOWNTO 0);

		rx_dec_lbk_ena			: IN  std_logic;
		rx_dec_lbk_tclk			: IN  std_logic;
		rx_dec_lbk_f1			: IN  std_logic_vector(1 DOWNTO 0);
		rx_dec_lbk_f2			: IN  std_logic_vector(1 DOWNTO 0);

		rx_enable			: IN  std_logic;
		rx_svalid			: IN  std_logic;
		--rx_samples			: IN  std_logic_vector(SAMPLE_W -1 DOWNTO 0);
		rx_i_samples			: IN  std_logic_vector(SAMPLE_W -1 DOWNTO 0);
		rx_q_samples			: IN  std_logic_vector(SAMPLE_W -1 DOWNTO 0);

		rx_data				: OUT std_logic;           -- Keep for hard decision mode
		rx_data_soft			: OUT signed(15 DOWNTO 0); -- Full soft metric
		rx_dvalid			: OUT std_logic;

		symbol_lock_count		: IN  std_logic_vector(9 DOWNTO 0);
		symbol_lock_threshold	: IN  std_logic_vector(15 DOWNTO 0);

		cst_lock_f1 			: OUT std_logic;
		cst_lock_f2				: OUT std_logic;
		cst_lock_time_f1 		: OUT std_logic_vector(15 DOWNTO 0);
		cst_lock_time_f2 		: OUT std_logic_vector(15 DOWNTO 0);
		cst_unlock_f1 			: OUT std_logic;
		cst_unlock_f2 			: OUT std_logic;

		-- Ports added for ILA in order to calibrate symbol lock threshold
		-- I'm only putting in F1 because that should be sufficient
		dbg_acc_i_f1			: OUT std_logic_vector(ACC_W -1 DOWNTO 0);
		dbg_acc_q_f1			: OUT std_logic_vector(ACC_W -1 DOWNTO 0);
		dbg_acc_iq_delta_f1		: OUT std_logic_vector(ACC_W -1 DOWNTO 0)

	);
END ENTITY msk_demodulator;

ARCHITECTURE rtl OF msk_demodulator IS
    CONSTANT LUT_FS  : integer := 2047;
    CONSTANT SPS_FP  : integer := 755719;   -- round(625000/54200 * 2^16)
    CONSTANT BUFLEN  : integer := 560;
    CONSTANT NSRCH   : integer := 24;        -- symbols per candidate in the phase search
    TYPE lut_t IS ARRAY(0 TO 1023) OF integer;
    FUNCTION build_lut(is_cos:boolean) RETURN lut_t IS VARIABLE r:lut_t; BEGIN
        FOR i IN 0 TO 1023 LOOP
            IF is_cos THEN r(i):=integer(round(cos(2.0*MATH_PI*real(i)/1024.0)*real(LUT_FS)));
            ELSE           r(i):=integer(round(sin(2.0*MATH_PI*real(i)/1024.0)*real(LUT_FS))); END IF;
        END LOOP; RETURN r; END;
    CONSTANT COS_ROM : lut_t := build_lut(true);
    CONSTANT SIN_ROM : lut_t := build_lut(false);
    FUNCTION rc(ph:signed) RETURN integer IS BEGIN RETURN COS_ROM(to_integer(unsigned(std_logic_vector(ph(31 DOWNTO 22))))); END;
    FUNCTION rs(ph:signed) RETURN integer IS BEGIN RETURN SIN_ROM(to_integer(unsigned(std_logic_vector(ph(31 DOWNTO 22))))); END;
    FUNCTION low32(x:signed) RETURN signed IS VARIABLE v:std_logic_vector(x'length-1 DOWNTO 0);
        BEGIN v:=std_logic_vector(x); RETURN signed(v(31 DOWNTO 0)); END;
    TYPE st_t IS (S_BUF, S_SEARCH, S_BOUND, S_RUN);
    SIGNAL cd_vin,cd_vout:std_logic:='0'; SIGNAL cd_x,cd_y:signed(19 DOWNTO 0):=(OTHERS=>'0'); SIGNAL cd_ang:signed(31 DOWNTO 0);
    -- second CORDIC: normalized angle discriminator for the combine() theta loop
    SIGNAL cd2_vin,cd2_vout:std_logic:='0'; SIGNAL cd2_x,cd2_y:signed(19 DOWNTO 0):=(OTHERS=>'0'); SIGNAL cd2_ang:signed(31 DOWNTO 0);
BEGIN
    U_cordic : ENTITY work.cordic_atan2 GENERIC MAP (XY_W=>20, ANG_W=>32, STAGES=>16)
        PORT MAP (clk=>clk, valid_in=>cd_vin, x_in=>cd_x, y_in=>cd_y, valid_out=>cd_vout, angle=>cd_ang);
    U_cordic2 : ENTITY work.cordic_atan2 GENERIC MAP (XY_W=>20, ANG_W=>32, STAGES=>16)
        PORT MAP (clk=>clk, valid_in=>cd2_vin, x_in=>cd2_x, y_in=>cd2_y, valid_out=>cd2_vout, angle=>cd2_ang);
    cst_lock_time_f1<=(OTHERS=>'0'); cst_lock_time_f2<=(OTHERS=>'0');
    cst_unlock_f1<='0'; cst_unlock_f2<='0';

    process(clk)
        TYPE ivec IS ARRAY(0 TO BUFLEN-1) OF integer; VARIABLE bi,bq:ivec;
        VARIABLE st:st_t:=S_BUF; VARIABLE bc,gpos,skipcnt:integer:=0; VARIABLE started:boolean:=false;
        VARIABLE cph,cfr,dph,p1,p2:signed(31 downto 0);
        VARIABLE frac,boundary_fp,sidx,wsym:integer;
        VARIABLE c1r,c1i,c2r,c2i:signed(47 downto 0); VARIABLE co,sn,tone_p:integer;
        VARIABLE cph2:signed(31 downto 0);   -- second per-tone carrier phase (offset fix)
        -- combine() BACK-END: residual theta Costas + imag arms + Massey 2T + boxplus
        CONSTANT PTS:integer:=3; CONSTANT ITS:integer:=7; CONSTANT ARMSH:integer:=22; -- theta gains + arm scale (fabric-scale validated)
        CONSTANT Q30:signed(31 downto 0):=to_signed(1073741824,32); -- 2^30 = 90 deg in 2^32 angle units
        VARIABLE cd2_ang_lat:signed(31 downto 0):=(others=>'0');     -- CORDIC angle latched at cd2_vout
        VARIABLE theta,freqc:signed(31 downto 0):=(others=>'0');
        VARIABLE co2,sn2:integer;
        VARIABLE y1r,y1i,y2r,y2i,ar,ai,eth:signed(63 downto 0);
        VARIABLE Xa,Yva,Xp,Yvp,enc_cur,enc_p,soft2t,maga,magb,magm:signed(39 downto 0);
        VARIABLE sgn2t:integer;
        CONSTANT PARITY:integer:=0;   -- 2T pairing parity (0 or 1); flip if frame sync never locks
        -- CONTINUOUS-reference correlator (phase NOT reset per symbol) feeding the 2T back-end
        VARIABLE p1c,p2c:signed(31 downto 0):=(others=>'0');
        VARIABLE fdacc:signed(31 downto 0):=(others=>'0');  -- continuous fd phase (never sawtooth-reset)
        VARIABLE c1cr,c1ci,c2cr,c2ci:signed(47 downto 0):=(others=>'0');
        VARIABLE cont_init:boolean:=false;
        -- lookahead streaming 2T state; ai_sgn latched for the delayed CORDIC discriminator
        VARIABLE Xh,Yvh:signed(39 downto 0):=(others=>'0'); VARIABLE have_arm,have_enc:boolean:=false; VARIABLE t2idx:integer:=0; VARIABLE ai_sgn:integer:=1;
        VARIABLE d1,d2,car,cai,e64,sd64:signed(63 downto 0);
        VARIABLE WORD_R4,pg,ps,ig,ish,slc,slt:integer; VARIABLE rx_tone_i:std_logic;
        -- per-tone symbol-lock detector (I^2 - Q^2 accumulated over slc symbols)
        VARIABLE aif1,aqf1,aif2,aqf2,iqd1,iqd2:signed(63 downto 0); VARIABLE cf1,cf2,iv,qv:integer;
        VARIABLE lkf1,lkf2:std_logic;
        -- search FSM state
        VARIABLE sc,sy,sk,sw,sidxs:integer; VARIABLE sp_fp:integer; VARIABLE stph:signed(31 downto 0);
        VARIABLE sc1r,sc1i,sc2r,sc2i:signed(47 downto 0); VARIABLE setot,sbest,ee1,ee2:signed(63 downto 0); VARIABLE sbs2:integer;

        PROCEDURE newsym IS VARIABLE tmp:integer; BEGIN c1r:=(others=>'0');c1i:=(others=>'0');c2r:=(others=>'0');c2i:=(others=>'0'); sidx:=0;
            c1cr:=(others=>'0');c1ci:=(others=>'0');c2cr:=(others=>'0');c2ci:=(others=>'0');  -- continuous accums reset per symbol; p1c/p2c must NOT reset
            tmp:=frac+SPS_FP; wsym:=tmp/65536; frac:=tmp-wsym*65536; if wsym<1 then wsym:=1; end if; p1:=cph; p2:=cph2; END;
        PROCEDURE accum(si,sq:integer) IS BEGIN
            co:=rc(p1); sn:=rs(p1); c1r:=c1r+to_signed(si*co+sq*sn,48); c1i:=c1i+to_signed(sq*co-si*sn,48);
            co:=rc(p2); sn:=rs(p2); c2r:=c2r+to_signed(si*co+sq*sn,48); c2i:=c2i+to_signed(sq*co-si*sn,48);
            -- CONTINUOUS-reference correlator: same tone freqs (cfr +/- WORD_R4), phase carried across symbols
            co:=rc(p1c); sn:=rs(p1c); c1cr:=c1cr+to_signed(si*co+sq*sn,48); c1ci:=c1ci+to_signed(sq*co-si*sn,48);
            co:=rc(p2c); sn:=rs(p2c); c2cr:=c2cr+to_signed(si*co+sq*sn,48); c2ci:=c2ci+to_signed(sq*co-si*sn,48);
            p1:=p1+to_signed(to_integer(cfr)+WORD_R4,32); p2:=p2+to_signed(to_integer(cfr)-WORD_R4,32);
            -- continuous correlator: FIXED WORD_R4 only (decoupled from front-end carrier loop); theta tracks full carrier offset
            p1c:=p1c+to_signed(WORD_R4,32); p2c:=p2c+to_signed(-WORD_R4,32);
            sidx:=sidx+1; END;
        PROCEDURE dump IS BEGIN
            co:=rc(dph); sn:=rs(dph);
            d1:=resize(c1r*co,64)+resize(c1i*sn,64); d2:=resize(c2r*co,64)+resize(c2i*sn,64);
            if d1>d2 then tone_p:=1; else tone_p:=0; end if;
            if tone_p=1 then car:=resize(c1r*co,64)+resize(c1i*sn,64); cai:=resize(c1i*co,64)-resize(c1r*sn,64);
            else car:=resize(c2r*co,64)+resize(c2i*sn,64); cai:=resize(c2i*co,64)-resize(c2r*sn,64); end if;
            cd_x<=resize(shift_right(car,28),20); cd_y<=resize(shift_right(cai,28),20); cd_vin<='1';
            if tone_p=1 then dph:=low32(resize(dph,64)+to_signed(WORD_R4,64)*wsym); else dph:=low32(resize(dph,64)-to_signed(WORD_R4,64)*wsym); end if;
            -- ===== combine() BACK-END on CONTINUOUS correlator c1c/c2c (front-end above UNTOUCHED) =====
            -- theta update from PREVIOUS symbol's latched CORDIC angle (delay-1); exactly one update per symbol
            if ai_sgn>=0 then eth:=resize(cd2_ang_lat,64)-resize(Q30,64);
            else               eth:=resize(cd2_ang_lat,64)+resize(Q30,64); end if;
            eth:=resize(low32(eth),64);
            freqc:=low32(resize(freqc,64)+shift_right(eth,ITS));
            theta:=low32(resize(theta,64)+shift_right(eth,PTS)+resize(freqc,64));
            co2:=rc(theta); sn2:=rs(theta);
            y1r:=resize(c1cr*co2,64)+resize(c1ci*sn2,64); y1i:=resize(c1ci*co2,64)-resize(c1cr*sn2,64);
            y2r:=resize(c2cr*co2,64)+resize(c2ci*sn2,64); y2i:=resize(c2ci*co2,64)-resize(c2cr*sn2,64);
            -- dominant tone by de-rotated energy (shift before square to bound width)
            d1:=resize(shift_right(y1r,18),32)*resize(shift_right(y1r,18),32)+resize(shift_right(y1i,18),32)*resize(shift_right(y1i,18),32);
            d2:=resize(shift_right(y2r,18),32)*resize(shift_right(y2r,18),32)+resize(shift_right(y2i,18),32)*resize(shift_right(y2i,18),32);
            if d2>d1 then ar:=y2r; ai:=y2i; else ar:=y1r; ai:=y1i; end if;
            -- feed CORDIC for NEXT symbol's theta update; latch sign(ai) to pair with the angle
            cd2_x<=resize(shift_right(ar,22),20); cd2_y<=resize(shift_right(ai,22),20); cd2_vin<='1';
            if ai<0 then ai_sgn:=-1; else ai_sgn:=1; end if;
            -- Massey 2T with one-symbol lookahead (pair symbol t2idx with next) + boxplus soft
            Xa:=resize(shift_right(y1i,ARMSH),40); Yva:=resize(shift_right(y2i,ARMSH),40);
            if have_arm then
                if ((t2idx+PARITY) mod 2)=0 then enc_cur:=(Xh+Xa)-(Yvh+Yva); else enc_cur:=(Xh+Xa)+(Yvh+Yva); end if;
                if have_enc then
                    maga:=abs(enc_cur); magb:=abs(enc_p);
                    if maga<magb then magm:=maga; else magm:=magb; end if;
                    if (enc_cur<0)=(enc_p<0) then soft2t:=magm; else soft2t:=-magm; end if;
                    if soft2t<0 then rx_data<='1'; else rx_data<='0'; end if;
                    if soft2t>32767 then rx_data_soft<=to_signed(32767,16);
                    elsif soft2t<-32768 then rx_data_soft<=to_signed(-32768,16);
                    else rx_data_soft<=resize(soft2t,16); end if;
                    rx_dvalid<='1';
                end if;
                enc_p:=enc_cur; have_enc:=true; t2idx:=t2idx+1;
            end if;
            Xh:=Xa; Yvh:=Yva; have_arm:=true;
            -- REAL symbol-lock: per-tone in-phase(car) vs quadrature/error(cai) energy over slc symbols
            iv:=to_integer(shift_right(car,24)); qv:=to_integer(shift_right(cai,24));
            if tone_p=1 then
                aif1:=aif1+to_signed(iv*iv,64); aqf1:=aqf1+to_signed(qv*qv,64); cf1:=cf1+1;
                if cf1>=slc then iqd1:=aif1-aqf1;
                    if iqd1>to_signed(slt,64) then lkf1:='1'; else lkf1:='0'; end if;
                    aif1:=(others=>'0'); aqf1:=(others=>'0'); cf1:=0; end if;
            else
                aif2:=aif2+to_signed(iv*iv,64); aqf2:=aqf2+to_signed(qv*qv,64); cf2:=cf2+1;
                if cf2>=slc then iqd2:=aif2-aqf2;
                    if iqd2>to_signed(slt,64) then lkf2:='1'; else lkf2:='0'; end if;
                    aif2:=(others=>'0'); aqf2:=(others=>'0'); cf2:=0; end if;
            end if;
            cst_lock_f1<=lkf1; cst_lock_f2<=lkf2;
            lpf_accum_f1 <=std_logic_vector(resize(shift_right(c1r,16),ACC_W)); f1_nco_adjust<=std_logic_vector(resize(shift_right(c1i,16),32));
            lpf_accum_f2 <=std_logic_vector(resize(shift_right(c2r,16),ACC_W)); f2_nco_adjust<=std_logic_vector(resize(shift_right(c2i,16),32));
            dbg_acc_iq_delta_f1<=std_logic_vector(resize(shift_right(iqd1,8),32)); END;
    begin
        if rising_edge(clk) then
            rx_dvalid<='0'; cd_vin<='0'; cd2_vin<='0';
            WORD_R4:=(to_integer(signed(rx_freq_word_f1))-to_integer(signed(rx_freq_word_f2)))/2;
            pg:=to_integer(unsigned(lpf_p_gain)); ps:=to_integer(unsigned(lpf_p_shift));
            ig:=to_integer(unsigned(lpf_i_gain)); ish:=to_integer(unsigned(lpf_i_shift));
            slc:=to_integer(unsigned(symbol_lock_count)); slt:=to_integer(unsigned(symbol_lock_threshold));
            if slc<1 then slc:=16; end if;
            -- live telemetry on the old dead ports (real carrier + lock state)
            -- (telemetry removed to expose accumulators cleanly)

            f1_error      <= std_logic_vector(cd_ang);                                -- CORDIC carrier error (watch it shrink)
            dbg_acc_i_f1  <= std_logic_vector(resize(shift_right(aif1,8),32));        -- f1 in-phase energy accum
            dbg_acc_q_f1  <= std_logic_vector(resize(shift_right(aqf1,8),32));        -- f1 quadrature energy accum
            f2_error      <= std_logic_vector(resize(shift_right(iqd2,8),32));        -- f2 LOCK METRIC (aif2-aqf2)


            if init='1' or rx_enable='0' then
                st:=S_BUF; bc:=0; gpos:=0; cph:=(others=>'0'); cph2:=(others=>'0');
                theta:=(others=>'0'); freqc:=(others=>'0'); Xp:=(others=>'0'); Yvp:=(others=>'0'); enc_p:=(others=>'0'); sgn2t:=-1;
                p1c:=(others=>'0'); p2c:=(others=>'0'); fdacc:=(others=>'0'); have_arm:=false; have_enc:=false; t2idx:=0; cont_init:=false;
                cfr:=to_signed((to_integer(signed(rx_freq_word_f1))+to_integer(signed(rx_freq_word_f2)))/2,32);
                dph:=(others=>'0'); frac:=0; cst_lock_f1<='0'; cst_lock_f2<='0';
                aif1:=(others=>'0');aqf1:=(others=>'0');aif2:=(others=>'0');aqf2:=(others=>'0');
                cf1:=0;cf2:=0;lkf1:='0';lkf2:='0';
            else
                -- async carrier update (any state)
                if cd_vout='1' then
                    e64:=to_signed(to_integer(cd_ang),64);
                    cfr:=resize(resize(cfr,64)+shift_right(e64*ig,ish),32);
                    if cfr>400000000 then cfr:=to_signed(400000000,32); elsif cfr<-400000000 then cfr:=to_signed(-400000000,32); end if;
                    if tone_p=1 then
                        cph :=low32(resize(cph,64) +shift_right(e64*pg,ps)+resize(cfr,64)*wsym);
                        cph2:=low32(resize(cph2,64)                       +resize(cfr,64)*wsym);
                    else
                        cph2:=low32(resize(cph2,64)+shift_right(e64*pg,ps)+resize(cfr,64)*wsym);
                        cph :=low32(resize(cph,64)                        +resize(cfr,64)*wsym);
                    end if;
                end if;
                -- latch CORDIC angle when valid; theta update itself happens once per symbol in dump
                if cd2_vout='1' then cd2_ang_lat:=cd2_ang; end if;
                if rx_svalid='1' then gpos:=gpos+1; end if;   -- global live-sample counter (all states)

                case st is
                when S_BUF =>
                    if rx_svalid='1' then
                        bi(bc):=to_integer(signed(rx_i_samples)); bq(bc):=to_integer(signed(rx_q_samples)); bc:=bc+1;
                        if bc=BUFLEN then
                            sc:=0; sy:=0; sk:=0; sp_fp:=0; sw:=SPS_FP/65536; stph:=(others=>'0');
                            sc1r:=(others=>'0');sc1i:=(others=>'0');sc2r:=(others=>'0');sc2i:=(others=>'0');
                            setot:=(others=>'0'); sbest:=to_signed(-1,64); sbs2:=0; st:=S_SEARCH;
                        end if;
                    end if;
                when S_SEARCH =>                               -- multi-cycle search: one buffer-sample per clock
                    sidxs:=(sp_fp/65536)+sk;
                    if sidxs<BUFLEN then
                        co:=rc(stph); sn:=rs(stph);
                        sc1r:=sc1r+to_signed(bi(sidxs)*co+bq(sidxs)*sn,48); sc1i:=sc1i+to_signed(bq(sidxs)*co-bi(sidxs)*sn,48);
                        sc2r:=sc2r+to_signed(bi(sidxs)*co-bq(sidxs)*sn,48); sc2i:=sc2i+to_signed(bq(sidxs)*co+bi(sidxs)*sn,48);
                    end if;
                    stph:=stph+to_signed(WORD_R4,32); sk:=sk+1;
                    if sk>=sw then                            -- symbol done
                        ee1:=resize(shift_right(sc1r,8)*shift_right(sc1r,8),64)+resize(shift_right(sc1i,8)*shift_right(sc1i,8),64);
                        ee2:=resize(shift_right(sc2r,8)*shift_right(sc2r,8),64)+resize(shift_right(sc2i,8)*shift_right(sc2i,8),64);
                        setot:=setot+abs(ee1-ee2);
                        sc1r:=(others=>'0');sc1i:=(others=>'0');sc2r:=(others=>'0');sc2i:=(others=>'0');
                        sp_fp:=sp_fp+SPS_FP; sw:=((sp_fp+SPS_FP)/65536)-(sp_fp/65536); if sw<1 then sw:=1; end if;
                        sk:=0; stph:=(others=>'0'); sy:=sy+1;
                        if sy>=NSRCH then                     -- candidate done
                            if setot>sbest then sbest:=setot; sbs2:=sc; end if;
                            setot:=(others=>'0'); sc:=sc+1; sp_fp:=sc*65536;
                            sw:=((sc*65536+SPS_FP)/65536)-sc; if sw<1 then sw:=1; end if; sy:=0;
                            if sc>=12 then boundary_fp:=sbs2*65536; st:=S_BOUND; end if;
                        end if;
                    end if;
                when S_BOUND =>                                -- advance one SPS per clock to first boundary >= gpos
                    if (boundary_fp/65536) < gpos then boundary_fp:=boundary_fp+SPS_FP;
                    else skipcnt:=(boundary_fp/65536)-gpos; frac:=boundary_fp-(boundary_fp/65536)*65536; started:=false; st:=S_RUN; end if;
                when S_RUN =>
                    if rx_svalid='1' then
                        if skipcnt>0 then skipcnt:=skipcnt-1;
                        else
                            if not started then newsym; p1c:=(others=>'0'); p2c:=(others=>'0');
                                have_arm:=false; have_enc:=false; t2idx:=0; theta:=(others=>'0'); freqc:=(others=>'0');
                                cd2_ang_lat:=(others=>'0'); ai_sgn:=1; Xh:=(others=>'0'); Yvh:=(others=>'0'); enc_p:=(others=>'0');
                                started:=true; end if;
                            accum(to_integer(signed(rx_i_samples)),to_integer(signed(rx_q_samples)));
                            if sidx=wsym then dump; newsym; end if;
                        end if;
                    end if;
                end case;
            end if;
        end if;
    end process;
END ARCHITECTURE rtl;
